import { Formula } from '../types/logic';

export function formulasEqual(a: Formula, b: Formula): boolean {
  if (a.type !== b.type) return false;
  if (a.type === 'atom' && b.type === 'atom') {
    return a.name === b.name;
  }
  if (a.type === 'not' && b.type === 'not') {
    return formulasEqual(a.operand, b.operand);
  }
  if (
    (a.type === 'and' && b.type === 'and') ||
    (a.type === 'or' && b.type === 'or') ||
    (a.type === 'implies' && b.type === 'implies') ||
    (a.type === 'iff' && b.type === 'iff')
  ) {
    return formulasEqual(a.left, b.left) && formulasEqual(a.right, b.right);
  }
  return false;
}

export function cloneFormula(f: Formula): Formula {
  if (f.type === 'atom') return { type: 'atom', name: f.name };
  if (f.type === 'not') return { type: 'not', operand: cloneFormula(f.operand) };
  return {
    type: f.type,
    left: cloneFormula(f.left),
    right: cloneFormula(f.right),
  };
}

export function countNodes(f: Formula): number {
  if (f.type === 'atom') return 1;
  if (f.type === 'not') return 1 + countNodes(f.operand);
  return 1 + countNodes(f.left) + countNodes(f.right);
}

export function getAtomicVariables(f: Formula): Set<string> {
  const vars = new Set<string>();
  function walk(node: Formula) {
    if (node.type === 'atom') {
      vars.add(node.name);
    } else if (node.type === 'not') {
      walk(node.operand);
    } else {
      walk(node.left);
      walk(node.right);
    }
  }
  walk(f);
  return vars;
}

/**
 * Returns all possible formulas generated by replacing a single occurrence of rom with 	o in oot.
 */
export function replaceSubformulaSingle(root: Formula, from: Formula, to: Formula): Formula[] {
  const results: Formula[] = [];

  // If the root itself matches rom, replacing root is one option
  if (formulasEqual(root, from)) {
    results.push(cloneFormula(to));
  }

  // Also explore replacing inside sub-expressions
  if (root.type === 'not') {
    const subReplacements = replaceSubformulaSingle(root.operand, from, to);
    for (const sub of subReplacements) {
      results.push({ type: 'not', operand: sub });
    }
  } else if (
    root.type === 'and' ||
    root.type === 'or' ||
    root.type === 'implies' ||
    root.type === 'iff'
  ) {
    const leftReplacements = replaceSubformulaSingle(root.left, from, to);
    for (const sub of leftReplacements) {
      results.push({ type: root.type, left: sub, right: cloneFormula(root.right) });
    }

    const rightReplacements = replaceSubformulaSingle(root.right, from, to);
    for (const sub of rightReplacements) {
      results.push({ type: root.type, left: cloneFormula(root.left), right: sub });
    }
  }

  return results;
}
